### 5. How to get the documentation of the numpy add function from the command line?

In [1]:
# python -c "import numpy as np; np. info(numpy.odd)"

### 6.create a null vector of size 10 but the fifth value which is 1

In [3]:
import numpy as np;
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


### 7.create a vector with values ranging from 10 to 49

In [4]:
import numpy as np;
arr = np.arange(10,50)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


### 8.Reverse a vector (first element becomes last)

In [5]:
import numpy as np;
z =np.arange(50)
z = z[::-1]
print(z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


### 3. create a null vector of size 10

In [6]:
import numpy as np;
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### 4.how to find the memory size of any array

In [7]:
import numpy as np;
z = np.zeros((10,10))
print("%d bytes" % (z.size * z.itemsize))

800 bytes


### 13. create a 10x10 array with random values and find the minimum and maximum values

In [8]:
import numpy as np;
arr = np.random.random((10,10))
arr_min,arr_max = arr.min(),arr.max()
print(arr_min,arr_max)

(0.009586240924372325, 0.9964993295803122)


### 14. create a random vector of size 30 and find the mean value

In [9]:
import numpy as np;
arr = np.random.random(30)
print(arr.mean())

0.5654580371467455


### 15.create a 2d array with 1 on the border and 0 inside

In [10]:
import numpy as np;
arr = np.ones((10,10))
arr[1:-1,1:-1] = 0
print(arr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


### 18. create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [12]:
import numpy as np;
arr = np.diag(1+np.arange(4),k=-1)
print(arr)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


### 19. create a 8X8 matrix and fill it with a checkerboard pattern

In [1]:
import numpy as np;
z = np.zeros((8.8),dtype=int)
z[:8:2,1:2] = 1
z[1::2,:8:2] =1
print(z)

TypeError: 'sage.rings.real_mpfr.RealLiteral' object cannot be interpreted as an index

### 20.consider a (6,7,8)shape array,what is the index(x,y,z)of the 100th element

In [2]:
import numpy as np;
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


### 16.how to add a border(filled with 0's) around an existing array

In [0]:
import numpy as np;
n=inpuit("give a number")
z=np.ones((int(n),int(n)))
z=np.pad(z,pad_width=1,mode=)